kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs
  labels:
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: nodejs
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: nodejs
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nodejs
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nodejs
  labels:
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: nodejs
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
